import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/Navbar";
import Modal from "./components/modals/modal";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Djangobnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content =(
    
      <p>Contenido</p>
  )
  return (
    <html lang="en">
      <body
        className
        ={`${geistSans.variable} ${geistMono.variable} 
        antialiased`}
      >
        <NavBar></NavBar>
        <div className="pt-32">
        {children}
        </div>s        
      </body>
    </html>
  );
}
